/**
 * schema.js — canonical data model for Bookwise.
 *
 * Entities live in the store (`src/store.js`) as plain objects in arrays. This
 * file is the single source of truth for their *shapes* — JSDoc typedefs that
 * IDEs can read, enum constants the rest of the app should pull from instead
 * of hard-coding strings, and factory functions so every creation site emits
 * a fully-populated object.
 *
 * Nothing here changes runtime behavior. The store and existing call sites
 * keep working unchanged. New code should prefer the factories so we stop
 * accumulating one-off shapes.
 *
 * Persistence: there is none yet — state is in-memory `useState`. When that
 * lands, this file is where the schema version + migration hooks belong.
 *
 * ── Field conventions ─────────────────────────────────────────────────────
 *   - `id`         opaque string, generated by `genId(prefix)`
 *   - `createdAt`  ISO-8601 string (new field — older entities may lack it)
 *   - `updatedAt`  ISO-8601 string (new field — older entities may lack it)
 *   - `date`       'YYYY-MM-DD' — calendar date in the user's local zone
 *
 * ── Known legacy / derived fields (kept for backcompat) ───────────────────
 *   Note.type     — singular, duplicates `types[0]`. Older list views read it.
 *   Note.isQuote  — derived from `types[0] === 'quote'`. Written at save time
 *                   but not re-derived on edit. Don't trust for new code; read
 *                   `types` instead.
 *   Note.text     — flattened plain-text view of `blocks`. Regenerated on save
 *                   via `blocksToText()`. Acts as the search index.
 *   Book.dateAdded — documented in CLAUDE.md but historically never set. The
 *                   `newBook()` factory below now populates it.
 *   Goal.recurrence undefined — legacy goals are treated as 'daily' (see
 *                   `goalsForDate` in store.js).
 */

// ─── ID generation ─────────────────────────────────────────────────────────
// Single canonical ID generator. Prefix narrows the namespace so a quick
// glance at an id tells you what kind of thing it points to.
export function genId(prefix = '') {
  const t = Date.now();
  const r = Math.random().toString(36).slice(2, 8);
  return prefix ? `${prefix}_${t}_${r}` : `${t}_${r}`;
}

// ─── Enums ─────────────────────────────────────────────────────────────────
// Mirror values already in use across the app. Imports from here should
// gradually replace inline string literals.

/** @typedef {'want_to_read' | 'reading' | 'finished' | 'abandoned'} BookStatus */
export const BOOK_STATUS = Object.freeze({
  WANT:      'want_to_read',
  READING:   'reading',
  FINISHED:  'finished',
  ABANDONED: 'abandoned',
});

/** @typedef {'Book' | 'Article' | 'Website' | 'PDF' | 'Newspaper' | 'Magazine' | 'Podcast' | 'Other'} BookFormat */
export const BOOK_FORMAT = Object.freeze({
  BOOK:      'Book',
  ARTICLE:   'Article',
  WEBSITE:   'Website',
  PDF:       'PDF',
  NEWSPAPER: 'Newspaper',
  MAGAZINE:  'Magazine',
  PODCAST:   'Podcast',
  OTHER:     'Other',
});
export const BOOK_FORMATS = Object.freeze(Object.values(BOOK_FORMAT));

// Cover swatch keys — actual gradient pairs live in theme.js `buildCovers()`.
/** @typedef {'sage' | 'amber' | 'navy' | 'rose' | 'plum' | 'slate'} CoverKey */
export const COVER_KEYS = Object.freeze(['sage', 'amber', 'navy', 'rose', 'plum', 'slate']);

/** @typedef {'quote' | 'insight' | 'question' | 'action' | 'summary' | 'connection'} NoteType */
export const NOTE_TYPE = Object.freeze({
  QUOTE:      'quote',
  INSIGHT:    'insight',
  QUESTION:   'question',
  ACTION:     'action',
  SUMMARY:    'summary',
  CONNECTION: 'connection',
});

/** @typedef {'paragraph' | 'quote' | 'thought' | 'heading' | 'bullet' | 'image'} BlockKind */
export const BLOCK_KIND = Object.freeze({
  PARAGRAPH: 'paragraph',
  QUOTE:     'quote',
  THOUGHT:   'thought',
  HEADING:   'heading',
  BULLET:    'bullet',
  IMAGE:     'image',
});

/** @typedef {'daily' | 'weekly' | 'monthly' | 'once'} GoalRecurrence */
export const GOAL_RECURRENCE = Object.freeze({
  DAILY:   'daily',
  WEEKLY:  'weekly',
  MONTHLY: 'monthly',
  ONCE:    'once',
});

// ─── Typedefs ──────────────────────────────────────────────────────────────

/**
 * @typedef {Object} User
 * @property {string} name        Display name. Empty string means "logged out" — App.js gates on this.
 * @property {string} email
 * @property {string} avatarSeed  Stable seed for the DiceBear avatar URL. Persists across sessions if set.
 */

/**
 * @typedef {Object} Book
 * @property {string}   id
 * @property {string}   title
 * @property {string}   author        May be '' for non-book formats (article/website).
 * @property {CoverKey} cover         Picked at random from COVER_KEYS on import.
 * @property {?string}  olKey         Open Library work key e.g. '/works/OL45883W'. null when added manually.
 * @property {?number}  coverId       Open Library cover image ID. null when no cover.
 * @property {number}   pageCount     Total pages; 0 if unknown.
 * @property {number}   currentPage   0..pageCount. Reading progress.
 * @property {string[]} genres        Free-form category labels. Up to ~3.
 * @property {string}   description
 * @property {BookStatus} status
 * @property {number}   rating        0..5, 0 = unrated.
 * @property {BookFormat} format
 * @property {string}   url           For online formats (article/website/pdf/podcast). '' otherwise.
 * @property {number=}  year          Publication year. Optional.
 * @property {string}   dateAdded     ISO timestamp. *Newly populated by `newBook()` — older books may lack it.*
 * @property {?string=} finishedAt    ISO timestamp, set when status transitions to 'finished'.
 */

/**
 * One element of `Note.blocks`. The factory lives in `src/components/editor/shared.js`
 * (`newBlock`) because the editor owns block construction — don't duplicate it here.
 *
 * @typedef {Object} Block
 * @property {string}    id
 * @property {BlockKind} type
 * @property {string}    text         For image blocks, this is the caption.
 * @property {string=}   attribution  Quote blocks only.
 * @property {?string=}  uri          Image blocks only. File URI from the picker.
 * @property {number=}   width        Image blocks only.
 * @property {number=}   height       Image blocks only.
 */

/**
 * @typedef {Object} Note
 * @property {string}     id
 * @property {string}     bookId          FK → Book.id. May be '' for unattached notes.
 * @property {string}     bookTitle       Denormalized at write time. Convenience for list views.
 * @property {string}     title           Free-form note title. May be ''.
 * @property {Block[]}    blocks          The actual content.
 * @property {NoteType[]} types           One or more selected types. Source of truth for "what kind of note".
 * @property {NoteType=}  type            LEGACY — duplicates types[0]. Older views still read it.
 * @property {string}     text            DERIVED — `blocksToText(blocks)`. Search index.
 * @property {string}     thinking        Reader's separate reflection layer.
 * @property {string=}    page            Free-form page reference, e.g. '42' or 'pp. 40-45'.
 * @property {string=}    chapter
 * @property {string[]}   tags            Uppercase, deduped. No separate Tag entity — derived as needed.
 * @property {string[]}   linkedNoteIds   IDs of notes this one points at. Only populated when types includes 'connection'.
 * @property {boolean}    isQuote         LEGACY — derived from types[0] === 'quote' at save time.
 * @property {boolean}    starred
 * @property {string}     date            'YYYY-MM-DD' — the reading date, not the createdAt.
 */

/**
 * Goal *template*. The actual per-day check-off lives in GoalCompletion.
 *
 * @typedef {Object} Goal
 * @property {string}         id
 * @property {string}         label        e.g. 'Read 20 pages'.
 * @property {string=}        tag          Free-form category tag. Optional.
 * @property {GoalRecurrence} recurrence
 * @property {number=}        weekday      0..6 (Sun..Sat). Required iff recurrence === 'weekly'.
 * @property {number=}        monthDay     1..31. Required iff recurrence === 'monthly'.
 * @property {string=}        dueDate      'YYYY-MM-DD'. Required iff recurrence === 'once'.
 * @property {string}         created      'YYYY-MM-DD' — goal never appears on dates before this.
 */

/**
 * One row per (goalId, date) the user has checked off. No `id` field — the
 * (goalId, date) pair is the natural key. Removing a goal cascades-deletes
 * its completions (see `removeGoal` in store.js).
 *
 * @typedef {Object} GoalCompletion
 * @property {string} goalId       FK → Goal.id.
 * @property {string} date         'YYYY-MM-DD'.
 * @property {string} completedAt  ISO timestamp.
 */

/**
 * One reflection per date. Upserted by date; deleted when text is empty.
 *
 * @typedef {Object} Reflection
 * @property {string} id
 * @property {string} date        'YYYY-MM-DD'. Unique within the array.
 * @property {string} text        Trimmed. Non-empty (empty deletes the row).
 * @property {string} updatedAt   ISO timestamp.
 */

/** @typedef {string} ActiveDay — 'YYYY-MM-DD'. Stored as a deduped string[] in the store. */

// ─── Factories ─────────────────────────────────────────────────────────────
// Every creation site should prefer these so new fields land everywhere at
// once. Pass a `patch` to override defaults — extra keys are spread through
// unchanged so callers can carry custom payloads (Open Library metadata etc.).

const nowIso = () => new Date().toISOString();
// Local-zone YYYY-MM-DD. Must match store.js — see the comment there.
const todayKey = () => {
  const d = new Date();
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
};
const pickCover = () => COVER_KEYS[Math.floor(Math.random() * COVER_KEYS.length)];

/**
 * Build a fully-formed Book. Required: title. Everything else defaults.
 * @param {Partial<Book> & { title: string }} patch
 * @returns {Book}
 */
export function newBook(patch) {
  if (!patch || !patch.title) throw new Error('newBook: title is required');
  return {
    id:          genId('bk'),
    olKey:       null,
    title:       patch.title,
    author:      '',
    cover:       pickCover(),
    coverId:     null,
    pageCount:   0,
    currentPage: 0,
    genres:      [],
    description: '',
    status:      BOOK_STATUS.WANT,
    rating:      0,
    format:      BOOK_FORMAT.BOOK,
    url:         '',
    dateAdded:   nowIso(),
    finishedAt:  null,
    ...patch,
  };
}

/**
 * Build a fully-formed Note. Required: at least one of `blocks` or `text`.
 *
 * The factory keeps the legacy fields populated (type, isQuote, text) so
 * older readers keep working. Callers should pass `blocks` and `types`; the
 * derived fields are filled in for them.
 *
 * @param {Partial<Note> & { blocks?: Block[], types?: NoteType[] }} patch
 * @param {(blocks: Block[]) => string} [flatten]  Optional `blocksToText` impl —
 *   pass it in to avoid circular imports from the editor module.
 * @returns {Note}
 */
export function newNote(patch = {}, flatten) {
  const blocks = patch.blocks || [];
  const types  = patch.types && patch.types.length ? patch.types : [NOTE_TYPE.INSIGHT];
  const primary = types[0];
  const text = patch.text != null
    ? patch.text
    : (flatten ? flatten(blocks) : '');

  return {
    id:            genId('n'),
    bookId:        '',
    bookTitle:     '',
    title:         '',
    blocks,
    types,
    type:          primary,                       // legacy mirror
    text,                                         // derived
    thinking:      '',
    page:          '',
    chapter:       '',
    tags:          [],
    linkedNoteIds: types.includes(NOTE_TYPE.CONNECTION) ? (patch.linkedNoteIds || []) : [],
    isQuote:       primary === NOTE_TYPE.QUOTE,   // legacy mirror
    starred:       false,
    date:          todayKey(),
    ...patch,
    // Re-apply derived fields after spread so callers can't accidentally
    // desync `type` / `isQuote` from `types`.
    type:    primary,
    isQuote: primary === NOTE_TYPE.QUOTE,
  };
}

/**
 * Build a fully-formed Goal. Validates the recurrence-specific field.
 * @param {Partial<Goal> & { label: string, recurrence: GoalRecurrence }} patch
 * @returns {Goal}
 */
export function newGoal(patch) {
  if (!patch || !patch.label) throw new Error('newGoal: label is required');
  if (!patch.recurrence)      throw new Error('newGoal: recurrence is required');

  switch (patch.recurrence) {
    case GOAL_RECURRENCE.WEEKLY:
      if (typeof patch.weekday !== 'number') throw new Error('newGoal: weekly recurrence needs weekday (0-6)');
      break;
    case GOAL_RECURRENCE.MONTHLY:
      if (typeof patch.monthDay !== 'number') throw new Error('newGoal: monthly recurrence needs monthDay (1-31)');
      break;
    case GOAL_RECURRENCE.ONCE:
      if (!patch.dueDate) throw new Error('newGoal: once recurrence needs dueDate (YYYY-MM-DD)');
      break;
  }

  return {
    id:         genId('g'),
    label:      patch.label,
    tag:        '',
    recurrence: patch.recurrence,
    created:    todayKey(),
    ...patch,
  };
}

/**
 * Build a GoalCompletion. (goalId, date) is the natural key.
 * @param {string} goalId
 * @param {string} date  'YYYY-MM-DD'
 * @returns {GoalCompletion}
 */
export function newGoalCompletion(goalId, date) {
  return { goalId, date, completedAt: nowIso() };
}

/**
 * Build a Reflection.
 * @param {string} date  'YYYY-MM-DD'
 * @param {string} text
 * @returns {Reflection}
 */
export function newReflection(date, text) {
  return { id: genId('r'), date, text, updatedAt: nowIso() };
}

/**
 * Build a fresh User. Empty `name` means logged out — App.js routes to LoginScreen.
 * @param {Partial<User>} [patch]
 * @returns {User}
 */
export function newUser(patch = {}) {
  return { name: '', email: '', avatarSeed: '', ...patch };
}

// ─── Tag normalization ─────────────────────────────────────────────────────
// Tags are stored uppercase, trimmed, no whitespace runs. Search call sites
// should run inputs through this too so comparison stays case-insensitive.
export function normalizeTag(input) {
  return String(input || '')
    .trim()
    .replace(/\s+/g, ' ')
    .toUpperCase();
}
